import java.io.IOException;
import java.time.LocalDate;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package aniscrap;

/**
 *
 * @author soviena
 */
public class Aniscrap extends javax.swing.JFrame {

    /**
     * Creates new form Aniscrap
     */
    public Aniscrap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_cari = new javax.swing.JPanel();
        txt_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        panel_out_cari = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_search_anime = new javax.swing.JList<>();
        lbl_judul = new javax.swing.JLabel();
        lbl_sinopsis = new javax.swing.JLabel();
        lbl_eps = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_sinopsis = new javax.swing.JTextArea();
        btn_tontont = new javax.swing.JButton();
        spin_eps = new javax.swing.JSpinner();
        panel_history = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        panel_out_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        list_search_anime.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_search_animeValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(list_search_anime);

        lbl_judul.setText("judul");

        lbl_sinopsis.setText("sinopsis");

        lbl_eps.setText("Episode");

        txt_sinopsis.setColumns(20);
        txt_sinopsis.setLineWrap(true);
        txt_sinopsis.setRows(5);
        txt_sinopsis.setWrapStyleWord(true);
        txt_sinopsis.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_sinopsis.setEnabled(false);
        jScrollPane3.setViewportView(txt_sinopsis);

        btn_tontont.setText("Tonton");
        btn_tontont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tontontActionPerformed(evt);
            }
        });

        spin_eps.setModel(new javax.swing.SpinnerNumberModel(1, 1, 2, 1));

        javax.swing.GroupLayout panel_out_cariLayout = new javax.swing.GroupLayout(panel_out_cari);
        panel_out_cari.setLayout(panel_out_cariLayout);
        panel_out_cariLayout.setHorizontalGroup(
            panel_out_cariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_out_cariLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_out_cariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addGroup(panel_out_cariLayout.createSequentialGroup()
                        .addGroup(panel_out_cariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_judul)
                            .addComponent(lbl_sinopsis))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_out_cariLayout.createSequentialGroup()
                        .addComponent(lbl_eps)
                        .addGap(18, 18, 18)
                        .addComponent(spin_eps)
                        .addGap(18, 18, 18)
                        .addComponent(btn_tontont)))
                .addContainerGap())
        );
        panel_out_cariLayout.setVerticalGroup(
            panel_out_cariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_out_cariLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_out_cariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addGroup(panel_out_cariLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbl_judul)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_sinopsis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_out_cariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_tontont)
                            .addComponent(spin_eps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_eps))))
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_cariLayout = new javax.swing.GroupLayout(panel_cari);
        panel_cari.setLayout(panel_cariLayout);
        panel_cariLayout.setHorizontalGroup(
            panel_cariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cariLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_cari)
                .addGap(18, 18, 18)
                .addComponent(btn_cari)
                .addContainerGap())
            .addComponent(panel_out_cari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_cariLayout.setVerticalGroup(
            panel_cariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cariLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_cariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cari)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_out_cari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cari", panel_cari);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Judul");

        jLabel2.setText("Episode");

        jLabel3.setText("Tanggal");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout panel_historyLayout = new javax.swing.GroupLayout(panel_history);
        panel_history.setLayout(panel_historyLayout);
        panel_historyLayout.setHorizontalGroup(
            panel_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_historyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jButton3))
                .addContainerGap(446, Short.MAX_VALUE))
        );
        panel_historyLayout.setVerticalGroup(
            panel_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_historyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_historyLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("History", panel_history);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        String query = this.txt_cari.getText();
        Anime[] animes = anoboy.searchAnime(query);
        this.list_search_anime.setListData(animes);
    }//GEN-LAST:event_btn_cariActionPerformed

    private void list_search_animeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_search_animeValueChanged
        Anime anime = this.list_search_anime.getSelectedValue();
        this.lbl_judul.setText(anime.getTitle());
        anoboy.getAnimeDetails(anime);
        anoboy.getEpList(anime);
        this.txt_sinopsis.setText(anime.getDesc());
        this.spin_eps.setModel(new javax.swing.SpinnerNumberModel(anime.getEpList().length, 1, anime.getEpList().length, 1));
    }//GEN-LAST:event_list_search_animeValueChanged

    private void btn_tontontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tontontActionPerformed
        Anime anime = this.list_search_anime.getSelectedValue();
        String link = anoboy.selectMirror(anime.getEpList()[anime.getEpList().length-Integer.valueOf(this.spin_eps.getModel().getValue().toString())]);
        link = Scrapper.uservideo(link);
        try {
            Runtime.getRuntime().exec("mpv "+link);
        } catch (IOException e) {
            System.out.println(e.toString());
            e.printStackTrace();
        }        
    }//GEN-LAST:event_btn_tontontActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aniscrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aniscrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aniscrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aniscrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aniscrap().setVisible(true);
            }
        });
    }

    private anoboy_online anoboy = new anoboy_online();
    private javax.swing.JSpinner spin_eps;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_tontont;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_eps;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JLabel lbl_sinopsis;
    private javax.swing.JList<Anime> list_search_anime;
    private javax.swing.JPanel panel_cari;
    private javax.swing.JPanel panel_history;
    private javax.swing.JPanel panel_out_cari;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextArea txt_sinopsis;
    // End of variables declaration//GEN-END:variables
}
